export const data = {
  nodes: [
    { id: "Internet", group: "www" },
    { id: "Arris TG2492LG-ZG (Modem+Router)", group: "Hardware" },
    { id: "TP-Link Deco Mesh (AP-1)", group: "Hardware" },
    { id: "Wifi AP-2", group: "Hardware" },
    { id: "Wifi AP-3", group: "Hardware" },
    { id: "MikroTik CSS610-8G-2S+in", group: "Hardware" },
    { id: "Synology DS920+", group: "Hardware" },
    { id: "Volume1", group: "Storage" },
    { id: "UM790", group: "Hardware" },
    { id: "Proxmox VE 8", group: "OS" },
    { id: "Tailscale", group: "Networking" },
    { id: "Ollama - Qwen 2.5 7B", group: "AI" },
    { id: "LXC 101 - Jellyfin", group: "Media" },
    { id: "LXC 102 - Postgres", group: "Storage" },
    { id: "LXC 104 - NGINX Proxy Manager", group: "Networking" },
    { id: "LXC 105 - n8n", group: "Automation" },
    { id: "LXC 106 - Tdarr", group: "Media" },
    { id: "VM 203 - Immich", group: "Media" },
    { id: "Planned - Nextcloud", group: "Cloud" },
    { id: "Planned - NoCoDB", group: "Storage" },
    { id: "Planned - MinIO", group: "Storage" },
    { id: "photos.dataandstories.com", group: "Public" },
    { id: "monitoring.dataandstories.com", group: "Public" },
    { id: "n8n.dataandstories.com", group: "Public" }
  ],
  links: [
    { source: "Internet", target: "Arris TG2492LG-ZG (Modem+Router)" },
    { source: "TP-Link Deco Mesh (AP-1)", target: "Wifi AP-2" },
    { source: "TP-Link Deco Mesh (AP-1)", target: "Wifi AP-3" },
    { source: "UM790", target: "Proxmox VE 8" },
    { source: "Proxmox VE 8", target: "LXC 101 - Jellyfin" },
    { source: "Proxmox VE 8", target: "LXC 104 - NGINX Proxy Manager" },
    { source: "Proxmox VE 8", target: "LXC 106 - Tdarr" },
    { source: "Proxmox VE 8", target: "VM 203 - Immich" },
    { source: "Proxmox VE 8", target: "Planned - Nextcloud" },
    { source: "Proxmox VE 8", target: "LXC 102 - Postgres" },
    { source: "Proxmox VE 8", target: "Planned - NoCoDB" },
    { source: "Proxmox VE 8", target: "Planned - MinIO" },
    { source: "Proxmox VE 8", target: "Tailscale" },
    { source: "Proxmox VE 8", target: "LXC 105 - n8n" },
    { source: "Proxmox VE 8", target: "Ollama - Qwen 2.5 7B" },
    { source: "Ollama - Qwen 2.5 7B", target: "LXC 105 - n8n" },
    { source: "UM790", target: "MikroTik CSS610-8G-2S+in" },
    { source: "Synology DS920+", target: "MikroTik CSS610-8G-2S+in" },
    { source: "TP-Link Deco Mesh (AP-1)", target: "MikroTik CSS610-8G-2S+in" },
    { source: "MikroTik CSS610-8G-2S+in", target: "Arris TG2492LG-ZG (Modem+Router)" },
    { source: "Arris TG2492LG-ZG (Modem+Router)", target: "TP-Link Deco Mesh (AP-1)" },
    { source: "Synology DS920+", target: "Volume1" },
    { source: "LXC 101 - Jellyfin", target: "Volume1" },
    { source: "VM 203 - Immich", target: "Volume1" },
    { source: "LXC 106 - Tdarr", target: "Volume1" },
    { source: "Planned - MinIO", target: "Volume1" },
    { source: "LXC 104 - NGINX Proxy Manager", target: "photos.dataandstories.com" },
    { source: "LXC 104 - NGINX Proxy Manager", target: "monitoring.dataandstories.com" },
    { source: "LXC 104 - NGINX Proxy Manager", target: "n8n.dataandstories.com" }
  ]
};